### ISSUE TITLE
Fresh install crashes

### ISSUE THREAD

**Issue by ssimono** [pb-/tasks#4]
Hi,

when installing tasks for the first time, the first run end up raising a `StopIteration` error. I fixed it by manually creating the store file (`touch $HOME/.tasks.json`)

I think the onboarding could be smoother by either

- Explaining on the README that the store file must be created
- Having a `tasks init` command or something that would do it
- Automatically creating the file if it is not there

**Comment by pb-** [comment]
Thanks for reporting :pray:. It should be fixed with the freshly released 2.5.1 :tada:.
